 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Plane Iter3                                                 
     # Surfaces =   6
     # Strips   =  47
     # Vortices = 366

  Sref = 0.44000       Cref = 0.29000       Bref =  1.5000    
  Xref = 0.31800       Yref =  0.0000       Zref = 0.50800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00181     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.03778
  CZtot =  -0.16303     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.16303
  CDtot =   0.00181
  CDvis =   0.00000     CDind = 0.0018117
  CLff  =   0.16303     CDff  = 0.0021762    | Trefftz
  CYff  =   0.00000         e =    0.7603    | Plane  

   flap            =   0.00000
   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.520166    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.325270
 x' mom.  Cl'|    Cla =  -0.000000    Clb =   0.005016
 y  mom.  Cm |    Cma =  -1.371261    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.120442

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   9.243395    CLr =   0.000000
 y  force CY |    CYp =   0.045330    CYq =   0.000000    CYr =   0.445666
 x' mom.  Cl'|    Clp =  -0.385210    Clq =   0.000000    Clr =   0.017467
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -10.519354    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.018152    Cnq =  -0.000000    Cnr =  -0.209057

                  flap         d1     aileron      d2     elevator     d3     rudder       d4 
                  ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.037392   CLd2 =  -0.000000   CLd3 =   0.007879   CLd4 =  -0.000000
 y  force CY |   CYd1 =  -0.000000   CYd2 =  -0.000306   CYd3 =  -0.000000   CYd4 =  -0.002738
 x' mom.  Cl'|   Cld1 =   0.000000   Cld2 =   0.006432   Cld3 =   0.000000   Cld4 =  -0.000037
 y  mom.  Cm |   Cmd1 =  -0.006380   Cmd2 =   0.000000   Cmd3 =  -0.019755   Cmd4 =  -0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =   0.000214   Cnd3 =   0.000000   Cnd4 =   0.001405
 Trefftz drag| CDffd1 =   0.000998 CDffd2 =   0.000000 CDffd3 =  -0.000199 CDffd4 =   0.000000
 span eff.   |    ed1 =  -0.000026    ed2 =  -0.000000    ed3 =   0.142935    ed4 =  -0.000000



 Neutral point  Xnp =   0.405976

 Clb Cnr / Clr Cnb  =  -0.498498    (  > 1 if spirally stable )
