 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Plane Iter3                                                 
     # Surfaces =   5
     # Strips   =  41
     # Vortices = 294

  Sref = 0.44000       Cref = 0.29000       Bref =  1.5000    
  Xref = 0.31800       Yref =  0.0000       Zref = 0.50800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08152     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =  -0.21040
  CZtot =  -1.09783     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.09783
  CDtot =   0.08152
  CDvis =   0.00000     CDind = 0.0815216
  CLff  =   1.09783     CDff  = 0.0986935    | Trefftz
  CYff  =   0.00000         e =    0.7602    | Plane  

   flap            =  25.00000
   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.377695    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.172918
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.067290
 y  mom.  Cm |    Cma =  -1.283296    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000001    Cnb =   0.079186

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   9.797543    CLr =  -0.000000
 y  force CY |    CYp =   0.203320    CYq =   0.000000    CYr =   0.169140
 x' mom.  Cl'|    Clp =  -0.379798    Clq =  -0.000000    Clr =   0.272296
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -10.695137    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.076078    Cnq =  -0.000002    Cnr =  -0.111546

                  flap         d1     aileron      d2     elevator     d3     rudder       d4 
                  ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.037392   CLd2 =  -0.000000   CLd3 =   0.007879   CLd4 =   0.000000
 y  force CY |   CYd1 =  -0.000000   CYd2 =  -0.001164   CYd3 =  -0.000000   CYd4 =  -0.002537
 x' mom.  Cl'|   Cld1 =   0.000000   Cld2 =   0.006493   Cld3 =   0.000000   Cld4 =  -0.000054
 y  mom.  Cm |   Cmd1 =  -0.006795   Cmd2 =  -0.000000   Cmd3 =  -0.019793   Cmd4 =  -0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =  -0.000246   Cnd3 =  -0.000000   Cnd4 =   0.001301
 Trefftz drag| CDffd1 =   0.006723 CDffd2 =   0.000000 CDffd3 =  -0.001322 CDffd4 =   0.000000
 span eff.   |    ed1 =  -0.000001    ed2 =  -0.000000    ed3 =   0.021096    ed4 =  -0.000000



 Neutral point  Xnp =   0.403012

 Clb Cnr / Clr Cnb  =   0.348107    (  > 1 if spirally stable )
