 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Plane Iter3                                                 
     # Surfaces =   5
     # Strips   =  41
     # Vortices = 294

  Sref = 0.44000       Cref = 0.29000       Bref =  1.5000    
  Xref = 0.31800       Yref =  0.0000       Zref = 0.50800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00188     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.05304
  CZtot =  -0.16728     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.16728
  CDtot =   0.00188
  CDvis =   0.00000     CDind = 0.0018798
  CLff  =   0.16728     CDff  = 0.0008693    | Trefftz
  CYff  =   0.00000         e =    2.0037    | Plane  

   flap            =   0.00000
   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.409024    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.322597
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.027265
 y  mom.  Cm |    Cma =  -0.969156    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.154557

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   8.116678    CLr =   0.000000
 y  force CY |    CYp =   0.033110    CYq =   0.000000    CYr =   0.352365
 x' mom.  Cl'|    Clp =  -0.382726    Clq =  -0.000000    Clr =   0.062744
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -6.823198    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.013061    Cnq =  -0.000000    Cnr =  -0.171363

                  flap         d1     aileron      d2     elevator     d3     rudder       d4 
                  ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.038362   CLd2 =   0.000000   CLd3 =   0.006366   CLd4 =  -0.000000
 y  force CY |   CYd1 =  -0.000000   CYd2 =  -0.001520   CYd3 =  -0.000000   CYd4 =  -0.004742
 x' mom.  Cl'|   Cld1 =   0.000000   Cld2 =   0.006550   Cld3 =   0.000000   Cld4 =  -0.000309
 y  mom.  Cm |   Cmd1 =  -0.009867   Cmd2 =   0.000000   Cmd3 =  -0.015144   Cmd4 =   0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =   0.000601   Cnd3 =   0.000000   Cnd4 =   0.002413
 Trefftz drag| CDffd1 =   0.000399 CDffd2 =  -0.000000 CDffd3 =   0.000556 CDffd4 =   0.000000
 span eff.   |    ed1 =  -0.000194    ed2 =   0.000000    ed3 =  -1.129996    ed4 =  -0.000000



 Neutral point  Xnp =   0.381745

 Clb Cnr / Clr Cnb  =   0.481795    (  > 1 if spirally stable )
