 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: aircraft                                                    
     # Surfaces =   6
     # Strips   =  96
     # Vortices =1152

  Sref =  8.3252       Cref = 0.76888       Bref =  11.798    
  Xref = 0.35282       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.01403     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00001     Cmtot =  -1.23470
  CZtot =  -0.91260     Cntot =   0.00001     Cn'tot =   0.00001

  CLtot =   0.91254
  CDtot =   0.01783
  CDvis =   0.00000     CDind =   0.01783
  CLff  =   0.91303     CDff  =   0.01668    | Trefftz
  CYff  =   0.00000         e =    0.9513    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.863377    CLb =  -0.000003
 y  force CY |    CYa =  -0.000091    CYb =  -0.286266
 x' mom.  Cl'|    Cla =   0.000015    Clb =  -0.143848
 y  mom.  Cm |    Cma =  -8.241488    Cmb =   0.000011
 z' mom.  Cn'|    Cna =   0.000091    Cnb =   0.056168

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000008    CLq =  23.969465    CLr =   0.000005
 y  force CY |    CYp =   0.164834    CYq =  -0.000281    CYr =   0.113155
 x' mom.  Cl'|    Clp =  -0.568177    Clq =   0.000033    Clr =   0.262661
 y  mom.  Cm |    Cmp =   0.000017    Cmq = -47.352036    Cmr =  -0.000016
 z' mom.  Cn'|    Cnp =  -0.111529    Cnq =   0.000293    Cnr =  -0.027288

                  aileron      d1     elevator     d2     rudder       d3 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.000000   CLd2 =   0.007117   CLd3 =  -0.974701
 y  force CY |   CYd1 =   0.001229   CYd2 =  -0.000000   CYd3 =   0.007812
 x' mom.  Cl'|   Cld1 =  -0.008069   Cld2 =   0.000000   Cld3 =   0.000732
 y  mom.  Cm |   Cmd1 =  -0.000000   Cmd2 =  -0.023126   Cmd3 =   6.570805
 z' mom.  Cn'|   Cnd1 =  -0.000527   Cnd2 =   0.000000   Cnd3 =  -0.000000
 Trefftz drag| CDffd1 =   0.000000 CDffd2 =   0.000080 CDffd3 =  -0.000001
 span eff.   |    ed1 =  -0.000000    ed2 =   0.010236    ed3 =  -0.000178



 Neutral point  Xnp =   1.433549

 Clb Cnr / Clr Cnb  =   0.266069    (  > 1 if spirally stable )
