 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: plane                                                       
     # Surfaces =   6
     # Strips   =  96
     # Vortices =1152

  Sref = 0.50000       Cref = 0.61157       Bref =  1.0000    
  Xref = 0.50000       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -9.11780     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.01121     Cltot =   0.00001     Cl'tot =   0.00001
  CYtot =  -0.00001     Cmtot =  -0.22250
  CZtot =  -0.03064     Cntot =   0.00001     Cn'tot =   0.00001

  CLtot =   0.03203
  CDtot =   0.00621
  CDvis =   0.00000     CDind =   0.00621
  CLff  =   0.03517     CDff  =   0.00118    | Trefftz
  CYff  =   0.00000         e =    0.1667    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   2.455969    CLb =  -0.000004
 y  force CY |    CYa =   0.000082    CYb =  -0.090714
 x' mom.  Cl'|    Cla =  -0.000023    Clb =   0.068746
 y  mom.  Cm |    Cma =  -1.376521    Cmb =  -0.000016
 z' mom.  Cn'|    Cna =  -0.000094    Cnb =   0.051094

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000037    CLq =   5.387795    CLr =   0.000017
 y  force CY |    CYp =  -0.061399    CYq =   0.000203    CYr =   0.102982
 x' mom.  Cl'|    Clp =  -0.173602    Clq =  -0.000050    Clr =  -0.033508
 y  mom.  Cm |    Cmp =  -0.000032    Cmq =  -4.581603    Cmr =  -0.000002
 z' mom.  Cn'|    Cnp =   0.028032    Cnq =  -0.000160    Cnr =  -0.073031

                  aileron      d1     elevator     d2     rudder       d3 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.000000   CLd2 =   0.000510   CLd3 =   5.997365
 y  force CY |   CYd1 =   0.002097   CYd2 =   0.000000   CYd3 =   0.003418
 x' mom.  Cl'|   Cld1 =  -0.003242   Cld2 =   0.000000   Cld3 =  -0.000000
 y  mom.  Cm |   Cmd1 =   0.000000   Cmd2 =   0.002425   Cmd3 =  -9.918060
 z' mom.  Cn'|   Cnd1 =  -0.001029   Cnd2 =   0.000000   Cnd3 =  -0.005371
 Trefftz drag| CDffd1 =   0.000000 CDffd2 =  -0.000099 CDffd3 =  -0.000015
 span eff.   |    ed1 =  -0.000000    ed2 =   0.018596    ed3 =   0.000313



 Neutral point  Xnp =   0.842773

 Clb Cnr / Clr Cnb  =   2.932481    (  > 1 if spirally stable )
