 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: test                                                        
     # Surfaces =   8
     # Strips   = 128
     # Vortices =1536

  Sref =  19.668       Cref =  1.1058       Bref =  21.344    
  Xref = 0.46073       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -8.12210     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00434     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.05688
  CZtot =  -0.01283     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.01331
  CDtot =   0.00248
  CDvis =   0.00000     CDind =   0.00248
  CLff  =   0.01216     CDff  =   0.00139    | Trefftz
  CYff  =  -0.00000         e =    0.0015    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.379874    CLb =  -0.000001
 y  force CY |    CYa =  -0.000041    CYb =  -0.240811
 x' mom.  Cl'|    Cla =  -0.000003    Clb =  -0.040012
 y  mom.  Cm |    Cma =  -2.584983    Cmb =   0.000093
 z' mom.  Cn'|    Cna =   0.000014    Cnb =   0.027875

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000001    CLq =   9.324805    CLr =   0.000000
 y  force CY |    CYp =  -0.089875    CYq =  -0.000067    CYr =   0.067745
 x' mom.  Cl'|    Clp =  -0.079135    Clq =  -0.000002    Clr =   0.011589
 y  mom.  Cm |    Cmp =   0.000001    Cmq = -11.130778    Cmr =   0.000007
 z' mom.  Cn'|    Cnp =   0.005545    Cnq =   0.000025    Cnr =  -0.008210

                  aileron      d1     elevator     d2     rudder       d3 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.000000   CLd2 =   0.002508   CLd3 =   0.025035
 y  force CY |   CYd1 =  -0.000658   CYd2 =  -0.000000   CYd3 =   0.015625
 x' mom.  Cl'|   Cld1 =  -0.002599   Cld2 =   0.000000   Cld3 =   0.001465
 y  mom.  Cm |   Cmd1 =   0.000000   Cmd2 =  -0.006732   Cmd3 =  -3.184814
 z' mom.  Cn'|   Cnd1 =   0.000065   Cnd2 =   0.000000   Cnd3 =  -0.003906
 Trefftz drag| CDffd1 =   0.000000 CDffd2 =  -0.000137 CDffd3 =   0.000001
 span eff.   |    ed1 =  -0.000000    ed2 =   0.000754    ed3 =   0.000001



 Neutral point  Xnp =   1.306442

 Clb Cnr / Clr Cnb  =   1.016868    (  > 1 if spirally stable )
