 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Plane Iter3                                                 
     # Surfaces =   5
     # Strips   =  41
     # Vortices = 294

  Sref = 0.44000       Cref = 0.29000       Bref =  1.5000    
  Xref = 0.61500E-01   Yref =  0.0000       Zref = 0.50800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00190     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.06675
  CZtot =  -0.16803     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.16803
  CDtot =   0.00190
  CDvis =   0.00000     CDind = 0.0018962
  CLff  =   0.16803     CDff  = 0.0009040    | Trefftz
  CYff  =   0.00000         e =    1.9442    | Plane  

   flap            =   0.00000
   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.403987    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.322321
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.027755
 y  mom.  Cm |    Cma =  -1.517837    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.182682

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   9.298523    CLr =   0.000000
 y  force CY |    CYp =   0.033484    CYq =   0.000000    CYr =   0.408477
 x' mom.  Cl'|    Clp =  -0.382683    Clq =  -0.000000    Clr =   0.066993
 y  mom.  Cm |    Cmp =   0.000000    Cmq =  -9.739864    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.014299    Cnq =  -0.000001    Cnr =  -0.234094

                  flap         d1     aileron      d2     elevator     d3     rudder       d4 
                  ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.038533   CLd2 =   0.000000   CLd3 =   0.006239   CLd4 =  -0.000000
 y  force CY |   CYd1 =   0.000000   CYd2 =  -0.001524   CYd3 =   0.000000   CYd4 =  -0.004738
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =   0.006550   Cld3 =  -0.000000   Cld4 =  -0.000312
 y  mom.  Cm |   Cmd1 =  -0.013009   Cmd2 =  -0.000000   Cmd3 =  -0.017831   Cmd4 =   0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =   0.000730   Cnd3 =  -0.000000   Cnd4 =   0.002827
 Trefftz drag| CDffd1 =   0.000415 CDffd2 =   0.000000 CDffd3 =   0.000562 CDffd4 =  -0.000000
 span eff.   |    ed1 =   0.000025    ed2 =  -0.000000    ed3 =  -1.064147    ed4 =   0.000000



 Neutral point  Xnp =   0.161449

 Clb Cnr / Clr Cnb  =   0.530897    (  > 1 if spirally stable )
