 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Plane Iter3                                                 
     # Surfaces =  11
     # Strips   =  77
     # Vortices = 510

  Sref = 0.44000       Cref = 0.29000       Bref =  1.5000    
  Xref = 0.61500E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00177     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =  -0.03873
  CZtot =  -0.16520     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.16520
  CDtot =   0.00177
  CDvis =   0.00000     CDind = 0.0017736
  CLff  =   0.16520     CDff  = 0.0005283    | Trefftz
  CYff  =  -0.00000         e =    3.2158    | Plane  

   flap            =   0.00000
   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.379817    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.390936
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.032079
 y  mom.  Cm |    Cma =  -0.862985    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.180446

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   7.902871    CLr =  -0.000000
 y  force CY |    CYp =   0.004967    CYq =  -0.000000    CYr =   0.433437
 x' mom.  Cl'|    Clp =  -0.382950    Clq =   0.000000    Clr =   0.077844
 y  mom.  Cm |    Cmp =  -0.000000    Cmq =  -8.692573    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.000040    Cnq =  -0.000000    Cnr =  -0.236596

                  flap         d1     aileron      d2     elevator     d3     rudder       d4 
                  ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.037267   CLd2 =  -0.000000   CLd3 =   0.006204   CLd4 =   0.000000
 y  force CY |   CYd1 =  -0.000000   CYd2 =  -0.001317   CYd3 =  -0.000000   CYd4 =  -0.004743
 x' mom.  Cl'|   Cld1 =   0.000000   Cld2 =   0.006263   Cld3 =   0.000000   Cld4 =  -0.000474
 y  mom.  Cm |   Cmd1 =  -0.006504   Cmd2 =   0.000000   Cmd3 =  -0.017768   Cmd4 =  -0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =   0.000705   Cnd3 =   0.000000   Cnd4 =   0.002827
 Trefftz drag| CDffd1 =   0.000246 CDffd2 =   0.000000 CDffd3 =   0.000763 CDffd4 =  -0.000000
 span eff.   |    ed1 =  -0.045939    ed2 =  -0.000001    ed3 =  -4.404718    ed4 =   0.000000



 Neutral point  Xnp =   0.118641

 Clb Cnr / Clr Cnb  =   0.540330    (  > 1 if spirally stable )
