 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Plane Iter3                                                 
     # Surfaces =   5
     # Strips   =  41
     # Vortices = 294

  Sref = 0.44000       Cref = 0.29000       Bref =  1.5000    
  Xref = 0.29000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00243     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =  -0.00000     Cmtot =  -0.22153
  CZtot =  -0.19893     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.19893
  CDtot =   0.00243
  CDvis =   0.00000     CDind = 0.0024265
  CLff  =   0.19893     CDff  = 0.0023311    | Trefftz
  CYff  =  -0.00000         e =    1.0568    | Plane  

   flap            =   0.00000
   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   6.593359    CLb =  -0.000000
 y  force CY |    CYa =  -0.000023    CYb =  -1.685008
 x' mom.  Cl'|    Cla =  -0.000001    Clb =  -0.437307
 y  mom.  Cm |    Cma =  -4.495768    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000012    Cnb =   1.001732

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =  26.723845    CLr =   0.000000
 y  force CY |    CYp =  -0.803032    CYq =  -0.000164    CYr =   2.223338
 x' mom.  Cl'|    Clp =  -0.784367    Clq =   0.000000    Clr =   0.644470
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -38.694870    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =   0.491701    Cnq =  -0.000085    Cnr =  -1.331879

                  flap         d1     aileron      d2     elevator     d3     rudder       d4 
                  ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.035380   CLd2 =   0.000000   CLd3 =   0.017437   CLd4 =   0.000000
 y  force CY |   CYd1 =  -0.000000   CYd2 =  -0.002931   CYd3 =  -0.000000   CYd4 =  -0.023150
 x' mom.  Cl'|   Cld1 =  -0.000000   Cld2 =   0.004862   Cld3 =   0.000000   Cld4 =  -0.006613
 y  mom.  Cm |   Cmd1 =  -0.031065   Cmd2 =  -0.000000   Cmd3 =  -0.052896   Cmd4 =   0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =   0.001445   Cnd3 =  -0.000000   Cnd4 =   0.014341
 Trefftz drag| CDffd1 =   0.000843 CDffd2 =   0.000000 CDffd3 =   0.000500 CDffd4 =   0.000000
 span eff.   |    ed1 =  -0.006299    ed2 =  -0.000000    ed3 =  -0.041352    ed4 =  -0.000000



 Neutral point  Xnp =   0.226740

 Clb Cnr / Clr Cnb  =   0.902188    (  > 1 if spirally stable )
