 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Plane Iter3                                                 
     # Surfaces =   5
     # Strips   =  41
     # Vortices = 294

  Sref = 0.44000       Cref = 0.29000       Bref =  1.5000    
  Xref = 0.61500E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00176     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =  -0.03842
  CZtot =  -0.16570     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.16570
  CDtot =   0.00176
  CDvis =   0.00000     CDind = 0.0017566
  CLff  =   0.16570     CDff  = 0.0007751    | Trefftz
  CYff  =  -0.00000         e =    2.2050    | Plane  

   flap            =   0.00000
   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.376287    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.323349
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.030226
 y  mom.  Cm |    Cma =  -0.899773    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.183042

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   7.883622    CLr =  -0.000000
 y  force CY |    CYp =   0.008500    CYq =  -0.000000    CYr =   0.408449
 x' mom.  Cl'|    Clp =  -0.382916    Clq =   0.000000    Clr =   0.077581
 y  mom.  Cm |    Cmp =  -0.000000    Cmq =  -8.718887    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.000296    Cnq =  -0.000000    Cnr =  -0.234153

                  flap         d1     aileron      d2     elevator     d3     rudder       d4 
                  ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =   0.037372   CLd2 =  -0.000000   CLd3 =   0.006203   CLd4 =   0.000000
 y  force CY |   CYd1 =  -0.000000   CYd2 =  -0.001553   CYd3 =  -0.000000   CYd4 =  -0.004738
 x' mom.  Cl'|   Cld1 =   0.000000   Cld2 =   0.006260   Cld3 =   0.000000   Cld4 =  -0.000474
 y  mom.  Cm |   Cmd1 =  -0.006411   Cmd2 =   0.000000   Cmd3 =  -0.017771   Cmd4 =  -0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =   0.000726   Cnd3 =   0.000000   Cnd4 =   0.002827
 Trefftz drag| CDffd1 =   0.000351 CDffd2 =   0.000000 CDffd3 =   0.000571 CDffd4 =   0.000000
 span eff.   |    ed1 =  -0.002701    ed2 =  -0.000000    ed3 =  -1.458469    ed4 =  -0.000000



 Neutral point  Xnp =   0.121125

 Clb Cnr / Clr Cnb  =   0.498387    (  > 1 if spirally stable )
